repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-ast

  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "80"]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
    -   id: pyupgrade

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
      - id: validate_manifest
